version: '3'
services:
        
        jackett:
                container_name: jackett
                image: linuxserver/jackett:latest
                restart: unless-stopped
                network_mode: host
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Paris # timezone
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - /opt/jackett/downloads:/downloads
                        - /opt/jackett/config:/config
  
        sonarr:
                container_name: sonarr
                image: linuxserver/sonarr:latest
                restart: unless-stopped
                network_mode: host
                environment:
                        - PUID=1000 # default user id, for downloaded files access rights
                        - PGID=1000 # default group id, for downloaded files access rights
                        - TZ=Europe/Paris # timezone
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - /opt/sonarr/config:/config # config files
                        - /mnt/:/tv # tv shows folder
                        - /opt/sonarr/downloads:/downloads # download folder
  
        radarr:
                container_name: radarr
                image: linuxserver/radarr:latest
                restart: unless-stopped
                network_mode: host
                environment:
                        - PUID=1000 # default user id, for downloaded files access rights
                        - PGID=1000 # default group id, for downloaded files access rights
                        - TZ=Europe/Paris # timezone
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - /opt/radarr/config:/config # config files
                        - /mnt/:/movies # movies folder
                        - /opt/radarr/downloads:/downloads # download folders

        ombi:
                build: /opt/docker-ombi-armhf/
                ports:
                        - 3579:3579
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Paris
                volumes:
                        - /opt/ombi/config:/config
                        
        resilio:
                image: linuxserver/resilio-sync:latest
                ports:
                        - "8888:8888"
                        - 55555:55555
                volumes:
                        - /opt/resilio/config:/config
                        - /mnt/:/sync
                        - /mnt/downloads:/downloads
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Paris
                restart: unless-stopped
