version: '3'

services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - 7878:7878
    volumes:
      - ./radarr/config/:/config
      - ${MOVIE_DIR}:/movies
      - ${STORAGE_DIR}/radarr:/downloads
    env_file:
      - .env

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config/:/config
      - ${TV_SHOW_DIR}:/tv
      - ${STORAGE_DIR}/sonarr:/downloads
    env_file:
      - .env
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - ./jackett/config/:/config
    env_file:
      - .env

  sync:
    image: nimmis/resilio-sync:latest
    container_name: sync
    volumes:
      - ${STORAGE_DIR}:/data
    ports:
      - 33333:33333
    user: "1000:1000"
    env_file:
      - .env
